apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: guardian.default.svc
webhooks:
- name: guardian.default.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    - deployments
    - services
    scope: "*"
  timeoutSeconds: 5
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: default
      name: guardian
      path: /api/validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxRENDQWJ5Z0F3SUJBZ0lSQUk5SjRMTmswOU9qdTNmcmdmTGFleGN3RFFZSktvWklodmNOQVFFTEJRQXcKRXpFUk1BOEdBMVVFQ2hNSWJuZGhibVJsY21Fd0hoY05NVGt3TlRJd01ETXhOVEF3V2hjTk1qSXdOVEEwTURNeApOVEF3V2pBVE1SRXdEd1lEVlFRS0V3aHVkMkZ1WkdWeVlUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFML0N3NEo4R1lrck10WG1BUkdIa2tmb1VDMmZXQWtCOXUzMGlkd3JiNE9mdHhJSDZ6cU8KTE9xU2hTVjQ1dzhHbHpMMENKUDRBdks4U0MvMnBWSWpZdXMzOG1wSkxWMVUwMWtud1E4bDNuNlBNUk4vOWQ3agpyenV5TzcreTdpeWVyUGFVNDRFczN1dTc2Rkc2N0ZncHp5bFkvTFZXWXo1S0lxdzlvdWMzZEhWSTZsMG5iZThjCnBJeGkzNm5SU0xkUk5ZYzlvY2lwTXhNOUh4Q3ZCRHFYZENtTWpDSHhXSkRzUWwwaGE1MDFXbjBPclpvTmlwWFkKVHBGYkZLR0ZDMHE5em5hQU4zVENROVJOUlBLclZIWkN5T0xNVmZUR0drR2JFVVRySjYrWThndVowNHRVNS9qdAp0bUV3UjdPK2ptR2plakZ0T0paWjJ5c1dFM3dJYjB1K0RpRUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFECkFnS3NNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTGN5MHIyWG1uNncKdUlaSUxrbFNlSTVaeWlQR1U1cGM2K1ExcXV6UE11R0xoOXZVVm5zTkFOdlU3ZWtiZUpCaDhhR2VsVWtZTWp3eQp4Q0lhQzUvTms3M2R4L1RSZjJSZGdRVUFkMDN5NFYrM29FV0lZalg1UWd6K1h6ajNZK1QyZ1p4Tmh2QUtvVEtSCnZodnhXMU10dXNJOXdKRktwZkpURytVUkdDRnpJYlZtUDB4clBHbTJhNGgvNW5QY1VCUS9EN29Mbzl6Z1Y5enAKeExpTUU2bFF2MGl1QjBBcFlwL1daaHNkRU5vcDYxVVFvaFk1QUExRVk2bDd3NDVtc3N1YUgwVFpMbTJIdHhmVwozOVBUZkZuSWp5U2x1L1hQdGFmZS9oVjNNUXFKRlQyNThZR2pOMUxHa1VoeW8yNjBVZWh5RTB6VFFMOExXVFpSCmdwZ1RFM1RLT1A4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==





